const CARD_WIDTH_RATIO = 5 / 6;
const CARD_HEIGHT_RATIO = 1.5;
const CARD_SAFE_GAP = 12;
const CARD_MIN_HEIGHT = 280;
const HEADER_HEIGHT_FALLBACK = 64;
const BOTTOM_TAB_HEIGHT_FALLBACK = 80;
const CONTROLS_HEIGHT_FALLBACK = 56;
const HEIGHT_UPDATE_THRESHOLD = 4;

export {
  BOTTOM_TAB_HEIGHT_FALLBACK,
  CARD_HEIGHT_RATIO,
  CARD_MIN_HEIGHT,
  CARD_SAFE_GAP,
  CARD_WIDTH_RATIO,
  CONTROLS_HEIGHT_FALLBACK,
  HEADER_HEIGHT_FALLBACK,
  HEIGHT_UPDATE_THRESHOLD,
};
