import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Tab, TabItem } from "@/shared/components/Tab";
import { HomeIcon, LayersIcon } from "lucide-react";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-dvh w-full flex flex-col justify-between`}
      >
        <div className="w-full h-full items-center justify-center">
          {children}
        </div>

        <Tab>
          <Link href="/">
            <TabItem icon={HomeIcon} label="홈" selected />
          </Link>

          <Link href="/deck">
            <TabItem icon={LayersIcon} label="덱" />
          </Link>
        </Tab>
      </body>
    </html>
  );
}
