import type { Metadata } from "next";
import "./globals.css";
import LayoutBodyClient from "@/app/ui/LayoutBodyClient";
import BottomTab from "@/shared/widgets/BottomTab";
import Header from "@/shared/widgets/Header";
import { LayoutChromeVisibilityProvider } from "@/shared/hooks";
import ToastProvider from "@/shared/components/ToastProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ko">
      <body
        className={`antialiased flex h-dvh w-full flex-col overflow-hidden`}
      >
        <LayoutChromeVisibilityProvider>
          <div className="mx-auto flex h-full w-full max-w-md flex-col">
            <Header />

            <LayoutBodyClient>{children}</LayoutBodyClient>

            <BottomTab />
          </div>
          <ToastProvider />
        </LayoutChromeVisibilityProvider>
      </body>
    </html>
  );
};

export default RootLayout;
