import type { Metadata } from "next";
import "./globals.css";
import BottomTab from "@/shared/widgets/BottomTab";
import Header from "@/shared/widgets/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ko">
      <body
        className={`antialiased flex h-dvh w-full flex-col overflow-hidden`}
      >
        <div className="mx-auto flex h-full w-full max-w-md flex-col">
          <Header />

          <div className="flex min-h-0 flex-1 pb-20">{children}</div>

          <BottomTab />
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
